USE HIGHCLOUD;
# KPI 1
SELECT * FROM CALANDERTABLE;
# KPI2
SELECT YEAR(DATEVALUE) AS YEARVALUE,concat(sum(maindata_final.Transported_Passengers)/1000000,"M") AS TOTALPASSENGERSTRANSPORTED,
CONCAT(sum(maindata_final.AVAILABLE_SEATS)/1000000,"M") AS TOTALAVIALABLESEATS ,
(SELECT CONCAT((ROUND( (sum(maindata_final.Transported_Passengers)/sum(maindata_final.AVAILABLE_SEATS)* 100),2)),"%")) 
AS LOADFACTOR
FROM maindata_final group by YEAR(DATEVALUE) ORDER BY YEAR(DATEVALUE);

SELECT YEAR(DATEVALUE) AS YEARVALUE,CONCAT("Q",(QUARTER(DATEVALUE))) AS QUARTER ,
sum(maindata_final.Transported_Passengers) AS TOTALPASSENGERSTRANSPORTED,
sum(maindata_final.AVAILABLE_SEATS) AS TOTALAVIALABLESEATS ,
(SELECT CONCAT((ROUND( (sum(maindata_final.Transported_Passengers)/sum(maindata_final.AVAILABLE_SEATS)* 100),2)),"%")) 
AS LOADFACTOR
FROM maindata_final group by YEAR(DATEVALUE),CONCAT("Q",(QUARTER(DATEVALUE))) 
ORDER BY YEAR(DATEVALUE),CONCAT("Q",(QUARTER(DATEVALUE)));

SELECT YEAR(DATEVALUE) AS YEARVALUE,MONTHNAME(DATEVALUE) AS MONTHNAME,sum(maindata_final.Transported_Passengers) AS TOTALPASSENGERSTRANSPORTED,
sum(maindata_final.AVAILABLE_SEATS) AS TOTALAVIALABLESEATS ,
(SELECT CONCAT((ROUND( (sum(maindata_final.Transported_Passengers)/sum(maindata_final.AVAILABLE_SEATS)* 100),2)),"%")) 
AS LOADFACTOR
FROM maindata_final group by YEAR(DATEVALUE),MONTHNAME(DATEVALUE),MONTH(DATEVALUE) ORDER BY YEAR(DATEVALUE) ASC,MONTH(DATEVALUE) ASC;

# KPI3

SELECT cg.CARRIER_GROUP AS CARRIERNAME,
CONCAT((ROUND( (sum(md.Transported_Passengers)/sum(md.AVAILABLE_SEATS)* 100),2)),"%")
AS LOADFACTOR 
FROM MAINDATA_FINAL AS MD
LEFT JOIN CARRIERGROUPS AS CG
ON MD.CARRIERGROUPID= CG.CARRIERGROUPID
GROUP BY CG.CARRIER_GROUP ORDER BY CG.CARRIER_GROUP;

SELECT AL.AIRLINE AS CARRIERNAME, CONCAT((ROUND( (sum(md.Transported_Passengers)/sum(md.AVAILABLE_SEATS)* 100),2)),"%")
AS LOADFACTOR FROM maindata_final as MD
LEFT JOIN
AIRLINES AS AL 
ON MD.AIRLINEID=AL.AIRLINEID
GROUP BY AL.AIRLINE ORDER BY (sum(md.Transported_Passengers)/sum(md.AVAILABLE_SEATS)* 100) DESC;

# KPI4
SELECT AL.AIRLINE AS CARRIERNAME , SUM(MD.TRANSPORTED_PASSENGERS) AS TOTAL_TRANSPORTED_PASSENGERS
FROM maindata_final AS MD
LEFT JOIN
AIRLINES AS AL ON
MD.AIRLINEID=AL.AIRLINEID
GROUP BY AL.AIRLINE ORDER BY SUM(MD.TRANSPORTED_PASSENGERS) DESC LIMIT 10;

# KPI5

SELECT FROM_TO_TO, COUNT(AIRLINEID) AS nUMBER_oF_fLIGHTS FROM MAINDATA_FINAL
GROUP BY FROM_TO_TO ORDER BY COUNT(AIRLINEID) DESC LIMIT 10;

# KPI6
SELECT CD.WEEKNAME , 
CONCAT(ROUND((SUM(MD.TRANSPORTED_PASSENGERS)/SUM(MD.AVAILABLE_SEATS)*100),2),"%") AS LOAD_FACTOR
FROM MAINDATA_FINAL AS MD 
LEFT JOIN
CALANDERTABLE AS CD
ON MD.DATEVALUE=CD.DATEVALUE
GROUP BY CD.WEEKNAME;

DESC DISTANCEGROUPS;
# KPI7
SELECT DG.DISTANCE,COUNT(MD.AIRLINEID) AS NUMBER_OF_FLIGHTS
FROM MAINDATA_FINAL AS MD
LEFT JOIN 
DISTANCEGROUPS AS DG
ON
MD.DISTANCEGROUPID=DG.DISTANCEGROUPID
GROUP BY DG.DISTANCE ORDER BY COUNT(MD.AIRLINEID) DESC LIMIT 10;










